#!/usr/bin/env bash

# A script to install and configure nginx

sudo apt-get upgrade

sudo apt-get upgrade

sudo apt-get install nginx

# nginx is installed now configuring files

sudo -c 'echo "Hello World!" > /var/www/html/index.html'

sudo /etc/init.d/nginx restart
